In [ ]:
dev = "AIzaSyB2PMkH6X8uhVXu9vsdpvoIsn7Y0d9bc-k"

## Pull All Comments

In [ ]:
import googleapiclient.discovery
import pandas as pd

api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = dev

youtube = googleapiclient.discovery.build(
    api_service_name, api_version, developerKey=DEVELOPER_KEY)

request = youtube.commentThreads().list(
    part="snippet",
    videoId="-GJgqIJsTME",
    maxResults=100
)

comments = []

# Execute the request.
response = request.execute()

# Get the comments from the response.
for item in response['items']:
    comment = item['snippet']['topLevelComment']['snippet']
    public = item['snippet']['isPublic']
    comments.append([
        comment['authorDisplayName'],
        comment['publishedAt'],
        comment['likeCount'],
        comment['textOriginal'],
        public
    ])

while (1 == 1):
  try:
   nextPageToken = response['nextPageToken']
  except KeyError:
   break
  nextPageToken = response['nextPageToken']
  # Create a new request object with the next page token.
  nextRequest = youtube.commentThreads().list(part="snippet", videoId="-GJgqIJsTME", maxResults=100, pageToken=nextPageToken)
  # Execute the next request.
  response = nextRequest.execute()
  # Get the comments from the next response.
  for item in response['items']:
    comment = item['snippet']['topLevelComment']['snippet']
    public = item['snippet']['isPublic']
    comments.append([
        comment['authorDisplayName'],
        comment['publishedAt'],
        comment['likeCount'],
        comment['textOriginal'],
        public
    ])

df = pd.DataFrame(comments, columns=['author', 'updated_at', 'like_count', 'text','public'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 695 entries, 0 to 694
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   author      695 non-null    object
 1   updated_at  695 non-null    object
 2   like_count  695 non-null    int64
 3   text        695 non-null    object
 4   public      695 non-null    bool
dtypes: bool(1), int64(1), object(3)
memory usage: 22.5+ KB

In [ ]:
response['items'][0]

{'kind': 'youtube#commentThread',
 'etag': 'cKlfN_LMrWMfDN6RNLrW6sGGd_U',
 'id': 'UgxRSavcEp5CYvqhmzx4AaABAg',
 'snippet': {'channelId': 'UC2utQmYluWGlhV-W0rTA2wg',
  'videoId': '-GJgqIJsTME',
  'topLevelComment': {'kind': 'youtube#comment',
   'etag': '7elxKA0SsyQwC6-vZRG4x0StMc8',
   'id': 'UgxRSavcEp5CYvqhmzx4AaABAg',
   'snippet': {'channelId': 'UC2utQmYluWGlhV-W0rTA2wg',
    'videoId': '-GJgqIJsTME',
    'textDisplay': 'Clovis my man',
    'textOriginal': 'Clovis my man',
    'authorDisplayName': '@alterego692',
    'authorProfileImageUrl': 'https://yt3.ggpht.com/ZuGTKzkbBfn9DDsce3t-QXQfmQeE-FBHgUfQEh1JKdKs0dfmXN4OW0XIcqmlVsLjN4M_e89S=s48-c-k-c0x00ffffff-no-rj',
    'authorChannelUrl': 'http://www.youtube.com/@alterego692',
    'authorChannelId': {'value': 'UCNlVcqeVUwfHOtKfVdffAiA'},
    'canRate': True,
    'viewerRating': 'none',
    'likeCount': 0,
    'publishedAt': '2023-10-23T16:43:21Z',
    'updatedAt': '2023-10-23T16:43:21Z'}},
  'canReply': True,
  'totalReplyCount': 0,
  'isPublic': True}}

In [ ]:
df.head(10)

,author,updated_at,like_count,text,public
0,@ActionBronsonMusic,2023-10-23T17:53:02Z,603,PARIS. WITH LOVE.,True
1,@paddy6891,2025-01-20T19:36:13Z,0,Clovis’s legendary speeches at Early June is 1...,True
2,@alexanderriedl1213,2025-01-09T11:40:31Z,0,"Action:""All I really care about is hanging out""",True
3,@zer0875,2024-11-07T23:53:05Z,0,I watch this guy to lower my blood pressure ❤,True
4,@gghstlr,2024-07-21T17:41:45Z,0,I want to put you and Clovis’ whole wardrobe i...,True
5,@treyvillanueva31,2024-07-10T06:40:56Z,0,Just applied and registered for my first class...,True
6,@EdwinLap,2024-06-08T21:23:13Z,0,I wish I could be there and will make it one o...,True
7,@sensology,2024-06-02T16:57:11Z,0,I like this a lot but nothing ever will top th...,True
8,@gregoiredoyon4569,2024-05-10T16:07:03Z,0,I need the name of the Bousquet wine at 8:15 min,True
9,@charlesruffing5606,2024-02-13T04:29:12Z,0,My Cats are junkies for this video...They try ...,True

## Sort by Likes and Get Top 10

In [ ]:
df.sort_values(by='like_count', ascending=False)[0:10]

,author,updated_at,like_count,text,public
679,@dirtsmegee,2023-10-23T15:05:54Z,1114,Action needs an 8 part series in every country...,True
582,@Nolanbrown480,2023-10-23T16:59:12Z,762,Clovis’ energy is absolutely unmatched. The pe...,True
0,@ActionBronsonMusic,2023-10-23T17:53:02Z,603,PARIS. WITH LOVE.,True
547,@ActionBronsonMusic,2023-10-23T17:53:02Z,603,PARIS. WITH LOVE.,True
684,@uknownutin3528,2023-10-23T15:01:03Z,549,One of the best food series on YouTube. LONG L...,True
693,@PinoPP,2023-10-23T12:30:09Z,278,One of the best and most authentic eating shows,True
633,@urbanprojectz,2023-10-23T15:59:02Z,179,This is a game changer for food/cooking/review...,True
657,@elmejortrabajodelmundo,2023-10-23T15:26:47Z,75,"""From Paris with Love"" makes me happy for real...",True
563,@yorkshireguy6671,2023-10-23T17:15:43Z,75,Action and Clovis in Paris always looks like t...,True
692,@cheng8841,2023-10-23T12:57:26Z,70,"""eight part series"" LETS GOOOOOO",True

#Pull all Comments for Multiple Videos

## 1. Get Comments Function

In [ ]:
import googleapiclient.discovery
import pandas as pd

api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = dev

youtube = googleapiclient.discovery.build(
    api_service_name, api_version, developerKey=DEVELOPER_KEY)


def getcomments(video):
  request = youtube.commentThreads().list(
      part="snippet",
      videoId=video,
      maxResults=100
  )

  comments = []

  # Execute the request.
  response = request.execute()

  # Get the comments from the response.
  for item in response['items']:
      comment = item['snippet']['topLevelComment']['snippet']
      public = item['snippet']['isPublic']
      comments.append([
          comment['authorDisplayName'],
          comment['publishedAt'],
          comment['likeCount'],
          comment['textOriginal'],
          comment['videoId'],
          public
      ])

  while (1 == 1):
    try:
     nextPageToken = response['nextPageToken']
    except KeyError:
     break
    nextPageToken = response['nextPageToken']
    # Create a new request object with the next page token.
    nextRequest = youtube.commentThreads().list(part="snippet", videoId=video, maxResults=100, pageToken=nextPageToken)
    # Execute the next request.
    response = nextRequest.execute()
    # Get the comments from the next response.
    for item in response['items']:
      comment = item['snippet']['topLevelComment']['snippet']
      public = item['snippet']['isPublic']
      comments.append([
          comment['authorDisplayName'],
          comment['publishedAt'],
          comment['likeCount'],
          comment['textOriginal'],
          comment['videoId'],
          public
      ])

  df2 = pd.DataFrame(comments, columns=['author', 'updated_at', 'like_count', 'text','video_id','public'])
  return df2

In [ ]:
df = getcomments('TYxqBTdOq24')
df

,author,updated_at,like_count,text,video_id,public
0,@aashishmeshram9892,2024-09-19T04:45:16Z,0,Thanks for your video..,TYxqBTdOq24,True
1,@3rjc11,2024-01-18T16:56:15Z,0,This was awesome thank you. Are these dashboar...,TYxqBTdOq24,True
2,@yaohun,2023-09-08T05:43:51Z,0,"Hi, sorry I am very new to SAP dashboard and h...",TYxqBTdOq24,True
3,@analyticswithadam,2023-05-10T06:12:50Z,4,Interested in thoughts on SAC compared with Po...,TYxqBTdOq24,True

## 2. For Loop for List of IDs

In [ ]:
df = pd.DataFrame()
for i in ['QOcP5OvSwlI','Lfzu74XDyco','TiS6vnju_mI','cYwioeHu_OU']:
  df2 = getcomments(i)
  df = pd.concat([df, df2])

In [ ]:
df

,author,updated_at,like_count,text,video_id,public
0,@asr494,2025-02-10T19:23:02Z,0,"Bas, could you make a IBCS standar video? I th...",QOcP5OvSwlI,True
1,@FrancizcoV,2025-01-29T02:45:18Z,0,Great video,QOcP5OvSwlI,True
2,@winsto4300,2024-12-20T14:17:10Z,0,Can data values ​​be added to the bar chart wh...,QOcP5OvSwlI,True
3,@ortj69,2024-12-12T14:22:37Z,0,Great tutorial. thx very much! It worked all p...,QOcP5OvSwlI,True
4,@FernandoMoreiraR,2024-12-02T03:52:57Z,0,Fantastic tutorial! Got enough info to make a ...,QOcP5OvSwlI,True
...,...,...,...,...,...,...
535,@theoffsideartist,2022-06-30T11:17:57Z,0,Cool,cYwioeHu_OU,True
536,@adamsikorski6380,2022-06-30T11:13:33Z,0,Ok that looks dope,cYwioeHu_OU,True
537,@UniversalFacts-unknown,2022-06-30T11:09:16Z,0,Amazing.. Thanks a lot .. Can you plz share da...,cYwioeHu_OU,True
538,@ahmedtareq5342,2022-06-30T11:04:25Z,0,🤩,cYwioeHu_OU,True
539,@JonathanCHANAL,2022-06-30T11:03:35Z,0,Realy nice design! well done ;),cYwioeHu_OU,True

In [ ]:
df.to_csv('output.csv', index=False)  # Save the DataFrame as a CSV file
from google.colab import files
files.download('output.csv')  # Download the file to your local system

In [ ]:
df['video_id'].value_counts()

video_id
cYwioeHu_OU    540
Lfzu74XDyco    446
TiS6vnju_mI    156
QOcP5OvSwlI     96
Name: count, dtype: int64